Use master
GO
IF DB_ID('LoginDB') IS NOT NULL
	BEGIN
		ALTER DATABASE LoginDB SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
		DROP DATABASE LoginDB
	END
GO
CREATE DATABASE LoginDB
GO

USE LoginDB
GO

CREATE TABLE MyLogin(
ID int IDENTITY(1,1) NOT NULL PRIMARY KEY,
UserName varchar(20) NOT NULL,
[Password] varchar(16) NOT NULL
)

INSERT INTO MyLogin VALUES ('Admin','Passw0rd')
INSERT INTO MyLogin VALUES ('UserOne','qwerty')
INSERT INTO MyLogin VALUES ('UserTwo','12345')